# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Celino South Beach Hotel
email: info@celinosouthbeach.com
description: Set to debut Fall 2017 on iconic Ocean Drive, The Celino Hotel will bring a new lifestyle of indulgence to South Beach, Florida. Subscribe to get updates here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://celinosouthbeach.com" # the base hostname & protocol for your site
reztripUrl: https://thecelinohotel.reztrip.com/
permalink: pretty
# Build settings
markdown: kramdown

# Reading Files
include:
  - _pages

collections:
  collection:
    output: true
